// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scratch.proto

package com.app.app;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.app.app.Empty)
    com.google.protobuf.MessageOrBuilder {
}
