// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scratch.proto

package com.app.app;

public interface MedicationListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.app.app.MedicationList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  java.util.List<com.app.app.med> 
      getMedList();
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  com.app.app.med getMed(int index);
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  int getMedCount();
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  java.util.List<? extends com.app.app.medOrBuilder> 
      getMedOrBuilderList();
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  com.app.app.medOrBuilder getMedOrBuilder(
      int index);

  /**
   * <code>string intake = 2;</code>
   */
  java.lang.String getIntake();
  /**
   * <code>string intake = 2;</code>
   */
  com.google.protobuf.ByteString
      getIntakeBytes();
}
