// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scratch.proto

package com.app.app;

/**
 * Protobuf type {@code com.app.app.MedicationList}
 */
public  final class MedicationList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.app.app.MedicationList)
    MedicationListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MedicationList.newBuilder() to construct.
  private MedicationList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MedicationList() {
    med_ = java.util.Collections.emptyList();
    intake_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MedicationList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              med_ = new java.util.ArrayList<com.app.app.med>();
              mutable_bitField0_ |= 0x00000001;
            }
            med_.add(
                input.readMessage(com.app.app.med.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            intake_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        med_ = java.util.Collections.unmodifiableList(med_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.app.app.MedicationProto.internal_static_com_app_app_MedicationList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.app.app.MedicationProto.internal_static_com_app_app_MedicationList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.app.app.MedicationList.class, com.app.app.MedicationList.Builder.class);
  }

  private int bitField0_;
  public static final int MED_FIELD_NUMBER = 1;
  private java.util.List<com.app.app.med> med_;
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  public java.util.List<com.app.app.med> getMedList() {
    return med_;
  }
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  public java.util.List<? extends com.app.app.medOrBuilder> 
      getMedOrBuilderList() {
    return med_;
  }
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  public int getMedCount() {
    return med_.size();
  }
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  public com.app.app.med getMed(int index) {
    return med_.get(index);
  }
  /**
   * <code>repeated .com.app.app.med med = 1;</code>
   */
  public com.app.app.medOrBuilder getMedOrBuilder(
      int index) {
    return med_.get(index);
  }

  public static final int INTAKE_FIELD_NUMBER = 2;
  private volatile java.lang.Object intake_;
  /**
   * <code>string intake = 2;</code>
   */
  public java.lang.String getIntake() {
    java.lang.Object ref = intake_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      intake_ = s;
      return s;
    }
  }
  /**
   * <code>string intake = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIntakeBytes() {
    java.lang.Object ref = intake_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      intake_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < med_.size(); i++) {
      output.writeMessage(1, med_.get(i));
    }
    if (!getIntakeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, intake_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < med_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, med_.get(i));
    }
    if (!getIntakeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, intake_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.app.app.MedicationList)) {
      return super.equals(obj);
    }
    com.app.app.MedicationList other = (com.app.app.MedicationList) obj;

    boolean result = true;
    result = result && getMedList()
        .equals(other.getMedList());
    result = result && getIntake()
        .equals(other.getIntake());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMedCount() > 0) {
      hash = (37 * hash) + MED_FIELD_NUMBER;
      hash = (53 * hash) + getMedList().hashCode();
    }
    hash = (37 * hash) + INTAKE_FIELD_NUMBER;
    hash = (53 * hash) + getIntake().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.app.app.MedicationList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.app.app.MedicationList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.app.app.MedicationList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.app.app.MedicationList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.app.app.MedicationList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.app.app.MedicationList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.app.app.MedicationList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.app.app.MedicationList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.app.app.MedicationList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.app.app.MedicationList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.app.app.MedicationList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.app.app.MedicationList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.app.app.MedicationList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.app.app.MedicationList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.app.app.MedicationList)
      com.app.app.MedicationListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.app.MedicationProto.internal_static_com_app_app_MedicationList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.app.MedicationProto.internal_static_com_app_app_MedicationList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.app.MedicationList.class, com.app.app.MedicationList.Builder.class);
    }

    // Construct using com.app.app.MedicationList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (medBuilder_ == null) {
        med_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        medBuilder_.clear();
      }
      intake_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.app.app.MedicationProto.internal_static_com_app_app_MedicationList_descriptor;
    }

    @java.lang.Override
    public com.app.app.MedicationList getDefaultInstanceForType() {
      return com.app.app.MedicationList.getDefaultInstance();
    }

    @java.lang.Override
    public com.app.app.MedicationList build() {
      com.app.app.MedicationList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.app.app.MedicationList buildPartial() {
      com.app.app.MedicationList result = new com.app.app.MedicationList(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (medBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          med_ = java.util.Collections.unmodifiableList(med_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.med_ = med_;
      } else {
        result.med_ = medBuilder_.build();
      }
      result.intake_ = intake_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.app.app.MedicationList) {
        return mergeFrom((com.app.app.MedicationList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.app.app.MedicationList other) {
      if (other == com.app.app.MedicationList.getDefaultInstance()) return this;
      if (medBuilder_ == null) {
        if (!other.med_.isEmpty()) {
          if (med_.isEmpty()) {
            med_ = other.med_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMedIsMutable();
            med_.addAll(other.med_);
          }
          onChanged();
        }
      } else {
        if (!other.med_.isEmpty()) {
          if (medBuilder_.isEmpty()) {
            medBuilder_.dispose();
            medBuilder_ = null;
            med_ = other.med_;
            bitField0_ = (bitField0_ & ~0x00000001);
            medBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMedFieldBuilder() : null;
          } else {
            medBuilder_.addAllMessages(other.med_);
          }
        }
      }
      if (!other.getIntake().isEmpty()) {
        intake_ = other.intake_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.app.app.MedicationList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.app.app.MedicationList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.app.app.med> med_ =
      java.util.Collections.emptyList();
    private void ensureMedIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        med_ = new java.util.ArrayList<com.app.app.med>(med_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.app.app.med, com.app.app.med.Builder, com.app.app.medOrBuilder> medBuilder_;

    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public java.util.List<com.app.app.med> getMedList() {
      if (medBuilder_ == null) {
        return java.util.Collections.unmodifiableList(med_);
      } else {
        return medBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public int getMedCount() {
      if (medBuilder_ == null) {
        return med_.size();
      } else {
        return medBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public com.app.app.med getMed(int index) {
      if (medBuilder_ == null) {
        return med_.get(index);
      } else {
        return medBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder setMed(
        int index, com.app.app.med value) {
      if (medBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMedIsMutable();
        med_.set(index, value);
        onChanged();
      } else {
        medBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder setMed(
        int index, com.app.app.med.Builder builderForValue) {
      if (medBuilder_ == null) {
        ensureMedIsMutable();
        med_.set(index, builderForValue.build());
        onChanged();
      } else {
        medBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder addMed(com.app.app.med value) {
      if (medBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMedIsMutable();
        med_.add(value);
        onChanged();
      } else {
        medBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder addMed(
        int index, com.app.app.med value) {
      if (medBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMedIsMutable();
        med_.add(index, value);
        onChanged();
      } else {
        medBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder addMed(
        com.app.app.med.Builder builderForValue) {
      if (medBuilder_ == null) {
        ensureMedIsMutable();
        med_.add(builderForValue.build());
        onChanged();
      } else {
        medBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder addMed(
        int index, com.app.app.med.Builder builderForValue) {
      if (medBuilder_ == null) {
        ensureMedIsMutable();
        med_.add(index, builderForValue.build());
        onChanged();
      } else {
        medBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder addAllMed(
        java.lang.Iterable<? extends com.app.app.med> values) {
      if (medBuilder_ == null) {
        ensureMedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, med_);
        onChanged();
      } else {
        medBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder clearMed() {
      if (medBuilder_ == null) {
        med_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        medBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public Builder removeMed(int index) {
      if (medBuilder_ == null) {
        ensureMedIsMutable();
        med_.remove(index);
        onChanged();
      } else {
        medBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public com.app.app.med.Builder getMedBuilder(
        int index) {
      return getMedFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public com.app.app.medOrBuilder getMedOrBuilder(
        int index) {
      if (medBuilder_ == null) {
        return med_.get(index);  } else {
        return medBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public java.util.List<? extends com.app.app.medOrBuilder> 
         getMedOrBuilderList() {
      if (medBuilder_ != null) {
        return medBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(med_);
      }
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public com.app.app.med.Builder addMedBuilder() {
      return getMedFieldBuilder().addBuilder(
          com.app.app.med.getDefaultInstance());
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public com.app.app.med.Builder addMedBuilder(
        int index) {
      return getMedFieldBuilder().addBuilder(
          index, com.app.app.med.getDefaultInstance());
    }
    /**
     * <code>repeated .com.app.app.med med = 1;</code>
     */
    public java.util.List<com.app.app.med.Builder> 
         getMedBuilderList() {
      return getMedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.app.app.med, com.app.app.med.Builder, com.app.app.medOrBuilder> 
        getMedFieldBuilder() {
      if (medBuilder_ == null) {
        medBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.app.app.med, com.app.app.med.Builder, com.app.app.medOrBuilder>(
                med_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        med_ = null;
      }
      return medBuilder_;
    }

    private java.lang.Object intake_ = "";
    /**
     * <code>string intake = 2;</code>
     */
    public java.lang.String getIntake() {
      java.lang.Object ref = intake_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        intake_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string intake = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIntakeBytes() {
      java.lang.Object ref = intake_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        intake_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string intake = 2;</code>
     */
    public Builder setIntake(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      intake_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string intake = 2;</code>
     */
    public Builder clearIntake() {
      
      intake_ = getDefaultInstance().getIntake();
      onChanged();
      return this;
    }
    /**
     * <code>string intake = 2;</code>
     */
    public Builder setIntakeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      intake_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.app.app.MedicationList)
  }

  // @@protoc_insertion_point(class_scope:com.app.app.MedicationList)
  private static final com.app.app.MedicationList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.app.app.MedicationList();
  }

  public static com.app.app.MedicationList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MedicationList>
      PARSER = new com.google.protobuf.AbstractParser<MedicationList>() {
    @java.lang.Override
    public MedicationList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MedicationList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MedicationList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MedicationList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.app.app.MedicationList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

