// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scratch.proto

package com.app.app;

public final class MedicationProto {
  private MedicationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_app_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_app_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_app_MedicationID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_app_MedicationID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_app_med_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_app_med_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_app_MedicationList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_app_MedicationList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_app_MedicationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_app_MedicationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rscratch.proto\022\013com.app.app\"\007\n\005Empty\"7\n" +
      "\014MedicationID\022\025\n\rallMedication\030\001 \001(\t\022\020\n\010" +
      "totalMed\030\002 \001(\t\"\026\n\003med\022\017\n\007medName\030\001 \001(\t\"?" +
      "\n\016MedicationList\022\035\n\003med\030\001 \003(\0132\020.com.app." +
      "app.med\022\016\n\006intake\030\002 \001(\t\"%\n\022MedicationRes" +
      "ponse\022\017\n\007message\030\001 \001(\t2\236\001\n\nMedication\022A\n" +
      "\016sendMedication\022\022.com.app.app.Empty\032\033.co" +
      "m.app.app.MedicationList\022M\n\017medicationTa" +
      "ken\022\031.com.app.app.MedicationID\032\037.com.app" +
      ".app.MedicationResponseB&\n\013com.app.appB\017" +
      "MedicationProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_app_app_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_app_app_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_app_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_com_app_app_MedicationID_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_app_app_MedicationID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_app_MedicationID_descriptor,
        new java.lang.String[] { "AllMedication", "TotalMed", });
    internal_static_com_app_app_med_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_app_app_med_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_app_med_descriptor,
        new java.lang.String[] { "MedName", });
    internal_static_com_app_app_MedicationList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_app_app_MedicationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_app_MedicationList_descriptor,
        new java.lang.String[] { "Med", "Intake", });
    internal_static_com_app_app_MedicationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_app_app_MedicationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_app_MedicationResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
