// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scratch.proto

package com.app.app;

public interface MedicationIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.app.app.MedicationID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string allMedication = 1;</code>
   */
  java.lang.String getAllMedication();
  /**
   * <code>string allMedication = 1;</code>
   */
  com.google.protobuf.ByteString
      getAllMedicationBytes();

  /**
   * <code>string totalMed = 2;</code>
   */
  java.lang.String getTotalMed();
  /**
   * <code>string totalMed = 2;</code>
   */
  com.google.protobuf.ByteString
      getTotalMedBytes();
}
